import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Hero from "../components/Hero";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Meal web  ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <AppRouterCacheProvider>
          <ThemeProvider>
            <Hero />
            {children}
            <ToastContainer theme="colored" />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
